class Database{
static List<Map<String,dynamic>> myList = [
    {
      "image":"assets/images/sandal1.jpeg",
      "name":"Ocayle",
      "price":"199",
    },
    {
      "image":"assets/images/sandal2.jpeg",
      "name":"Xami",
      "price":"129",
    },
    {
      "image":"assets/images/sandal3.jpeg",
      "name":"Lana",
      "price":"129",
    },
    {
      "image":"assets/images/sandal4.jpeg",
      "name":"Ullani",
      "price":"119",
    },
    {
      "image":"assets/images/sandal5.jpeg",
      "name":"Ocayle",
      "price":"199",
    },
    {
      "image":"assets/images/sandal6.jpeg",
      "name":"Xami",
      "price":"129",
    },
  ];
}